- tests/googletest/test-fragmentUtils.cpp
Without this header the file wouldn't compile on macOS 12.6
> Include array STL header

- R/matrix.R
- tests/testthat/test-matrix_transforms.R
- tests/testthat/test-matrix_utils.R
``` r
library(BPCells)
mock_matrix <- function(ngenes, ncells) {
cell.means <- 2^stats::runif(ngenes, 2, 10)
cell.disp <- 100 / cell.means + 0.5
cell.data <- matrix(stats::rnbinom(ngenes * ncells,
mu = cell.means,
size = 1 / cell.disp
), ncol = ncells)
rownames(cell.data) <- sprintf("Gene_%s", formatC(seq_len(ngenes),
width = 4, flag = 0
))
colnames(cell.data) <- sprintf("Cell_%s", formatC(seq_len(ncells),
width = 3, flag = 0
))
cell.data
}
tmpdir <- tempdir()
mat <- mock_matrix(30, 20)
path <- normalizePath(tempfile(tmpdir = tmpdir), mustWork = FALSE)
obj <- write_matrix_dir(mat = as(mat, "dgCMatrix"), dir = path)
#> Warning: Matrix compression performs poorly with non-integers.
#> • Consider calling convert_matrix_type if a compressed integer matrix is intended.
#> This message is …
```
> respect `matrix_type` when coerced into matrix

- r/NEWS.md
- r/R/trackplots.R
- r/tests/testthat/test-trackplots.R
Changes `trackplot_coverage()` so to prevent data conversion from tibble to named vector when dealing with only one cluster.
- Added test cases for `trackplot_coverage()` to check for crashing out in both multi-cluster and single-cluster cases
- Added test for `trackplot_coverage()` return data type
> [r] Fix `trackplot_coverage()` when interacting with single clusters

- README.md
- r/NEWS.md
- r/R/trackplots.R
- r/index.md
- r/tests/testthat/test-trackplots.R
- r/vignettes/pbmc3k.Rmd
Various small changes to coverage plots and genome peak plots to handle smaller motifs better.
- Created at least a single arrow for peaks that are not long enough for the pre-determined minimum arrow segment length.  Note, in very small peaks the arrow may go out of bounds of the peak itself, which will likely also need to be fixed in the future.
- Fixed an issue where the head_only boolean flow in `trackplot_create_arrow_segs()` did not properly assign values to the start and end position if a strand was negative.
- Fixed an issue arising from tracks smaller than 500 bp in `trackplot_coverage()`
- Added a small test case for the head_only boolean flow in `trackplot_create_arrow_segs()`
- Added tests for small regions in `trackplot_coverage()`
> [r] fix trackplot bugs with small tracks/motifs

- r/NEWS.md
- r/R/trackplots.R
- r/man/trackplot_combine.Rd
- r/man/trackplot_coverage.Rd
Add several improvements to the `trackplot_combine` layout logic.
For plots without sideplots, before and after are as follows:
- Preserve vertical margins when stacking scalebars, and make sure they won't remove the x-axis label of the plot above them
- Detect when tracks change the genomic region they are plotting and show a new x-axis appropriately
- Fix the `trackplot_gene()` color legend to always show both + and - strand
- Fix `trackplot_scalebar()` to change the font size as requested (before it just affected track height)
- Switch color legends to vertical layout by default, and only use horizontal layout when a side plot is present
- Shorten the y-axis label for `trackplot_coverage()` to reduce (though not eliminate) the likelihood of the label getting cut off
And, when …
> [r] Improve trackplot_combine layout logic

- r/src/clustering.cpp
This adds a defensive check for input dimensions to avoid messy crashes/bugs when users pass in mis-formed KNN results to `knn_to_geodesic_graph()`
> [cpp] Add dims check in `build_umap_graph_cpp`

- r/NEWS.md
- r/src/R_array_io.cpp
- r/tests/testthat/test-matrix_io.R
Rcpp started warning about out-of-bounds access stating `subscript out of bounds (index 0 >= vector size 0)` on some tests. This was due to length-zero arrays in BPCells matrices arising from e.g. single element arrays with perfectly compressed data arrays (0 bits per element in the bitpacking data array).
Now we avoid accessing an index of a possibly-empty array and use an alternate method to get a data pointer.
> [r] Fix Rcpp warning about out-of-bounds access

- cpp/CMakeLists.txt
- cpp/tests/test-bp128.cpp
- r/src/Makevars.in
- r/src/bitpacking_io.cpp
- r/src/bpcells-cpp/simd/bp128.h
- r/src/bpcells-cpp/simd/bp128/bp128-Nx128.cpp
- r/src/bpcells-cpp/simd/bp128/bp128-helper-inl.h
- r/src/bpcells-cpp/simd/bp128/d1_maxbits.cpp
- r/src/bpcells-cpp/simd/bp128/d1_pack.cpp
- r/src/bpcells-cpp/simd/bp128/d1_unpack.cpp
- r/src/bpcells-cpp/simd/bp128/d1z_maxbits.cpp
- r/src/bpcells-cpp/simd/bp128/d1z_pack.cpp
- r/src/bpcells-cpp/simd/bp128/d1z_unpack.cpp
- r/src/bpcells-cpp/simd/bp128/diff_maxbits.cpp
- r/src/bpcells-cpp/simd/bp128/diff_pack.cpp
- r/src/bpcells-cpp/simd/bp128/diff_unpack.cpp
- r/src/bpcells-cpp/simd/bp128/for_maxbits.cpp
- r/src/bpcells-cpp/simd/bp128/for_pack.cpp
- r/src/bpcells-cpp/simd/bp128/for_unpack.cpp
- r/src/bpcells-cpp/simd/bp128/vanilla_maxbits.cpp
- r/src/bpcells-cpp/simd/bp128/vanilla_pack.cpp
- r/src/bpcells-cpp/simd/bp128/vanilla_unpack.cpp
When re-running some benchmarks, I observed 30-40% performance regressions for in-memory BP-128 compression relative to the pre-Gentech code (e.g. commit 91ed30). This turned out to be caused by the shift from macro-based code to C++ lambda-based code. For the BP-128 kernels, it is extremely important to avoid loops or function calls in the core pack/unpack function, but the lambda-based code was not properly inlining some of the lambdas.
This PR makes two important changes and one unimportant change that may be useful for the future.
**Important change 1:** Shift back to using pure C macros to construct the core BP-128 kernels. These are the `BP128_*_DECL` macros, which try to isolate the core bitpacking logic in one place so all the variants need only specify their arguments and the …
> Performance fix for BP-128 kernels

- r/NEWS.md
- r/configure
- r/configure.win
- r/src/Makevars.in
The local `./configure` for BPCells does not have a mechanism for setting `HDF5_CFLAGS` and `HDF5_LIBS` external to the script, as do other `./configure` scripts; it relies only on its own internal mechanisms for determining the flags for interacting with hdf5. We do not provide hdf5 in the standard locations, but rather provide it from an Lmod module, so the include files and libraries for hdf5 are not in standard system locations..
This just uses a little bashiness to set the compilation and link flag variables to current environment variables if these are provided, otherwise it uses the current defaults.  With these changes, compilation against an hdf5 in a nonstandard location works correctly with
```
HDF5_CFLAGS="-I${HDF5_INCLUDE}" HDF5_LIBS="-L${HDF5_LIB} -lhdf5" R CMD INSTALL …
```
> enable setting HDF5_CFLAGS and HDF5_LIBS external to ./configure

- .github/workflows/deploy-docs.yml
- .github/workflows/deploy-full-website.yml
- .github/workflows/deploy-reference.R
- r/DESCRIPTION
Creates a PR to html-docs whenever something is pushed to `main`, and performs the website building workflow indicated in `Wiki/Tool Development Workflows`
Title of PR is `Update docs for commit: <most_recent_commit_message>`
Message of PR is the git log of the most recent commit.  I am open to changing this to something that better describes the changes to documentation.
Example of how this would look can be found [here](https://github.com/immanuelazn/BPCells/pull/17).  This PR was created as a result of pushing this commit into my personal BPCells main branch.
We can also make it perform an automatic push to `html-docs`, if that is preferred.  We can also set this up to be a manually triggered workflow.
> [r] add automatic website building

- r/NEWS.md
- r/R/clustering.R
- r/man/cluster.Rd
- r/tests/testthat/test-clustering.R
- r/tests/testthat/test-singlecell_utils.R
Currently, `cluster_graph_leiden()` by default will output a number of clusters that scales approximately linearly with number of cells if the `resolution` parameter is held constant. This is generally not good and leads to problems like [this](https://github.com/bnprks/BPCells/issues/125#issuecomment-2359162884) where people get thousands of clusters called on large datasets.
This pull request does the following:
- Changes default `objective_function` from `CPM` to `modularity` sets default `resolution` back to 1.
- Moves clustering-related tests to a new file and makes a basic test to confirm that the clustering functions at least don't crash. I don't know of a good way of validating the clustering is working, so not crashing seems good enough for now.
Here is the benchmarking data to …
> [r] Adjust default parameters for `cluster_graph_leiden()`

- r/configure
This is to address some confusion that popped up in #149, where the error message didn't print out the quotation marks from the original command correctly
> [r] Fix awk typo in configure error message

- r/NEWS.md
- r/R/matrix.R
- r/R/singlecell_utils.R
- r/tests/testthat/test-singlecell_utils.R
As reported in #173, `pseudobulk_matrix()` assumes that all input matrices are type "double", which results in type confusion in some circumstances. While fixing this, I also noticed an issue in `pseudobulk_matrix`'s use of `parallel_split`, which would needlessly split up a matrix even if no parallelism was requested (slight potential performance/memory hit). I did a small refactor to make `parallel_split` easier to use correctly and resolve the issue in `pseudobulk_matrix`
Changes in this PR:
- Always cast inputs to `pseudobulk_matrix()` to type `double`
- Adjust `parallel_split` logic to not do any splitting if `threads <= 1`
- Adjust other usages of `parallel_split` to take advantage of not needing the conditional logic anymore
> [r] Fix type confusion in `pseudobulk_matrix()` and clean up `parallel_split()`

- r/DESCRIPTION
- r/NEWS.md
- r/R/atac_utils.R
- r/R/trackplots.R
This is mainly to tag an exact BPCells version for use in final benchmark results for the paper -- just a quick release announcement and update to the relevant deprecation warnings
> [r] 0.3.0 release announcement

- r/NEWS.md
- r/R/atac_utils.R
- r/tests/testthat/test-atac_utils.R
I noticed that `call_peaks_macs` wasn't printing out helpful error messages because they get trapped inside the `mclapply` call sometimes. (This came up because I accidentally broke macs in my local virtualenv, but when tests failed there weren't good error messages)
Previous output when MACS hit an error while running peak calling:
```
Warning message:
In parallel::mclapply(file_names, function(shell_file) { :
2 function calls resulted in an error
```
New output when MACS hits an error while running peak calling:
```
2024-12-20 16:01:21  Error running MACS for cluster: a_group
MACS log file written to: /tmp/RtmpwYXpma/file30a8322a9d7527/macs-test/output/a_group/log.txt
2024-12-20 16:01:21  Error running MACS for cluster: b_group
MACS log file written to: …
```
> [r] Improve error printing in `call_peaks_macs`

- r/R/singlecell_utils.R
Self explanatory, writing `L` after a number feels unnecessary.
> [r] Use whole number check instead of integer check for `pseudobulk_matrix()`

- r/NEWS.md
- r/R/matrix.R
- r/man/matrix_R_conversion.Rd
- r/tests/testthat/test-matrix_stats.R
Pretty self explanatory, added a few lines to allow matrix_stats, to be a little more input matrix agnostic.  I thought it would be better for us to automatically try to convert with a try, except block.  This should allow downstream caller functions to also work with `matrix` and `dgcMatrix`.
Also added a small helper conversion between `matrix` and `IterableMatrix`.
> [r] provide more mat input flex to `matrix_stats()`

- r/src/bpcells-cpp/matrixIterators/MatrixIndexSelect.h
- r/tests/testthat/test-matrix_utils.R
Motivation: The subset assignment operator results in a concatenation layer followed by a re-ordering of the rows/cols. We don't want this outer re-order layer to prevent any parallelism or other optimizations available on the inner layers, so it's time to have all the stats specialized for row/col re-ordering.
This just adds specializations for `computeMatrixStats`, `rowSums`, and `colSums` along with tests
> [cpp] Improve stats calculation in row/col reorder

- r/R/geneScores.R
- r/tests/testthat/test-atac_utils.R
Within the codeblock conditioned on param `AddArchRBug`, all ranges are deemed as overlaps when no ranges are actually present.  This results in all `upstream` and `downstream` values being set to 0.  
The bug occurs because `overlaps` becomes set to `integer(0)`.  When running `range[-overlaps,]`, the intended effect would be to remove 0 rows, rather than removing all rows.
I fixed this just by doing a length condition check after calculating `overlaps`.  Also added a small test for this function, for range with and without nesting.
> [r] fix nesting bug in `range_distance_to_nearest()`

- README.md
- r/index.md
Fix for issue #230, updating the suggested conda channel, since the `anaconda` channel has licensing concerns for many users.
> [docs] Update suggested conda channel

- r/NEWS.md
- r/R/fragments.R
This should fix #229, which is likely caused by a combination of specific installation procedures and the BPCells R package getting built before the GenomicRanges package is installed.
For what it's worth, I don't reproduce issue #229 on a fresh `renv` environment when running `renv::install("bnprks/BPCells/r@v0.3.0")`, followed later by `renv::install("bioc::GenomicRanges")`.
Since we want these conversion functions to work regardless of how/when BPCells was installed, wrapping this in an `rlang::on_load()` call makes it a load-time rather than an install-time check.
> [r] Fix check to enable GRanges conversion 

- r/NEWS.md
- r/src/matrix_io.cpp
- r/tests/testthat/test-matrix_io.R
Fixes #211
Pretty self explanatory.  Added a conditional to `hdf5_group_exists_cpp` to ensure we're not checking for a group in a file that doesn't exist.
> [cpp] add fix for `write_matrix_hdf5()` when overwriting nonexistent file

- r/R/transforms.R
- r/man/IterableMatrix-methods.Rd
- r/src/bpcells-cpp/matrixTransforms/Pow.cpp
- r/src/bpcells-cpp/matrixTransforms/Pow.h
- r/tests/testthat/test-matrix_transforms.R
I realized that we shouldn't support negative exponents for powers, since that would mess up all the zero values in the matrix. Just updated a few bounds checks to make that happen
> [r][cpp] Force pow to use strictly positive exponent

- r/src/fragment_io.cpp
- r/src/fragment_utils.cpp
- r/src/matrix_utils.cpp
I noticed that rowMaxs and colMaxs didn't check for users pressing ctrl-C when I was working on a recent PR, so I did a sweep of all the `*.cpp` files in the `src` dir to make sure everything quits promptly when ctrl-C is pressed.
My rule of thumb for check frequency is that every column is fine for a matrix since there are 1000s of columns usually, but for fragments it's necessary to check within each chromosome since a single chromosome might be too long to wait through.
> [r][cpp] Add missing user interrupt checks

- r/NEWS.md
- r/R/RcppExports.R
- r/src/RcppExports.cpp
- r/src/bpcells-cpp/matrixIterators/ImportMatrix10xHDF5.cpp
- r/src/matrix_io.cpp
- r/tests/testthat/test-matrix_io.R
Hi, @bnprks 
When I tried to use `BPCells::write_matrix_10x_hdf5` in `loupeR` from https://github.com/10XGenomics/loupeR , the program `louper.exe create --input=<h5file> --output=<cloupe file>` raised an error:
```
indices: cannot convert dataset to int64
```
When I change the original `uint32/64_t` to `int32/64_t` in "indices" and "indptr", the error is fixed. Maybe it would be better if the HDF5 files written by `BPCells` use data types more consistent with 10x's expected formats, to improve compatibility with downstream tools.
> Use `int32_t` and `int64_t` for 10x H5 writing function

- r/src/bpcells-cpp/fragmentIterators/RegionSelect.cpp
- r/src/bpcells-cpp/fragmentIterators/StoredFragments.cpp
- r/src/bpcells-cpp/fragmentUtils/InsertionIterator.h
Running on my Arch Linux machine, I get crashes in the test suite caused by taking &vec[0] of an empty vector in InsertionIterator.h. No data would be read/written in the empty case, but to avoid these crashes I switched to using
pointer arithmetic here and in any similar calls to `std::memmove` in the rest of the codebase.
> [cpp] Remove unsafe address vector address refs

- .gitignore
- r/NEWS.md
- r/configure
- r/configure.win
- r/tools/hwy-test.cpp.in
We use a package named highway, which helps with added efficiency in automatically choosing the best CPU intrinsics for vectorization based on your architecture.
Previously, there was a previous bug during compilation, which did not allow BPCells to utilize Highway if it was already installed. This was fixed. However, I suspect that if you have an older version of highway, installation would fail, and would not fall back to our packaged version of highway.  We can see this in #285, where `BroadcastLane`, which is part of highway is not being detected.
I made some general improvements to `configure` for highway,  in both the logging and the detection.
I added some version detection within `hwy-test.cpp`, which is version templated through `hwy-test.cpp.in`.  I also added a fallback to …
> [cpp] add version detection for highway
